import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"
 
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}


export const countries = [
  {
    Name: "Afghanistan",
    Code2: "AF",
    Code3: "AFG",
    Code3Digits: 4,
  },
  {
    Name: "Aland Islands",
    Code2: "AX",
    Code3: "ALA",
    Code3Digits: 248,
  },
  {
    Name: "Albania",
    Code2: "AL",
    Code3: "ALB",
    Code3Digits: 8,
  },
  {
    Name: "Algeria",
    Code2: "DZ",
    Code3: "DZA",
    Code3Digits: 12,
  },
  {
    Name: "American Samoa",
    Code2: "AS",
    Code3: "ASM",
    Code3Digits: 16,
  },
  {
    Name: "Andorra",
    Code2: "AD",
    Code3: "AND",
    Code3Digits: 20,
  },
  {
    Name: "Angola",
    Code2: "AO",
    Code3: "AGO",
    Code3Digits: 24,
  },
  {
    Name: "Anguilla",
    Code2: "AI",
    Code3: "AIA",
    Code3Digits: 660,
  },
  {
    Name: "Antarctica",
    Code2: "AQ",
    Code3: "ATA",
    Code3Digits: 10,
  },
  {
    Name: "Antigua and Barbuda",
    Code2: "AG",
    Code3: "ATG",
    Code3Digits: 28,
  },
  {
    Name: "Argentina",
    Code2: "AR",
    Code3: "ARG",
    Code3Digits: 32,
  },
  {
    Name: "Armenia",
    Code2: "AM",
    Code3: "ARM",
    Code3Digits: 51,
  },
  {
    Name: "Aruba",
    Code2: "AW",
    Code3: "ABW",
    Code3Digits: 533,
  },
  {
    Name: "Australia",
    Code2: "AU",
    Code3: "AUS",
    Code3Digits: 36,
  },
  {
    Name: "Austria",
    Code2: "AT",
    Code3: "AUT",
    Code3Digits: 40,
  },
  {
    Name: "Azerbaijan",
    Code2: "AZ",
    Code3: "AZE",
    Code3Digits: 31,
  },
  {
    Name: "Azores",
    Code2: "AC",
    Code3: "AZO",
    Code3Digits: 951,
  },
  {
    Name: "Bahamas",
    Code2: "BS",
    Code3: "BHS",
    Code3Digits: 44,
  },
  {
    Name: "Bahrain",
    Code2: "BH",
    Code3: "BHR",
    Code3Digits: 48,
  },
  {
    Name: "Bangladesh",
    Code2: "BD",
    Code3: "BGD",
    Code3Digits: 50,
  },
  {
    Name: "Barbados",
    Code2: "BB",
    Code3: "BRB",
    Code3Digits: 52,
  },
  {
    Name: "Belarus",
    Code2: "BY",
    Code3: "BLR",
    Code3Digits: 112,
  },
  {
    Name: "Belgium",
    Code2: "BE",
    Code3: "BEL",
    Code3Digits: 56,
  },
  {
    Name: "Belize",
    Code2: "BZ",
    Code3: "BLZ",
    Code3Digits: 84,
  },
  {
    Name: "Benin",
    Code2: "BJ",
    Code3: "BEN",
    Code3Digits: 204,
  },
  {
    Name: "Bermuda",
    Code2: "BM",
    Code3: "BMU",
    Code3Digits: 60,
  },
  {
    Name: "Bhutan",
    Code2: "BT",
    Code3: "BTN",
    Code3Digits: 64,
  },
  {
    Name: "Bolivia",
    Code2: "BO",
    Code3: "BOL",
    Code3Digits: 68,
  },
  {
    Name: "Bosnia and Herzegovina",
    Code2: "BA",
    Code3: "BIH",
    Code3Digits: 70,
  },
  {
    Name: "Botswana",
    Code2: "BW",
    Code3: "BWA",
    Code3Digits: 72,
  },
  {
    Name: "Bouvet Island",
    Code2: "BV",
    Code3: "BVT",
    Code3Digits: 74,
  },
  {
    Name: "Brazil",
    Code2: "BR",
    Code3: "BRA",
    Code3Digits: 76,
  },
  {
    Name: "British Indian Ocean Territory",
    Code2: "IO",
    Code3: "IOT",
    Code3Digits: 86,
  },
  {
    Name: "British Virgin Islands",
    Code2: "VG",
    Code3: "VGB",
    Code3Digits: 92,
  },
  {
    Name: "Brunei Darussalam",
    Code2: "BN",
    Code3: "BRN",
    Code3Digits: 96,
  },
  {
    Name: "Bulgaria",
    Code2: "BG",
    Code3: "BGR",
    Code3Digits: 100,
  },
  {
    Name: "Burkina Faso",
    Code2: "BF",
    Code3: "BFA",
    Code3Digits: 854,
  },
  {
    Name: "Burundi",
    Code2: "BI",
    Code3: "BDI",
    Code3Digits: 108,
  },
  {
    Name: "Cambodia",
    Code2: "KH",
    Code3: "KHM",
    Code3Digits: 116,
  },
  {
    Name: "Cameroon",
    Code2: "CM",
    Code3: "CMR",
    Code3Digits: 120,
  },
  {
    Name: "Canada",
    Code2: "CA",
    Code3: "CAN",
    Code3Digits: 124,
  },
  {
    Name: "Canary Islands",
    Code2: "IC",
    Code3: "CAI",
    Code3Digits: 958,
  },
  {
    Name: "Cape Verde",
    Code2: "CV",
    Code3: "CPV",
    Code3Digits: 132,
  },
  {
    Name: "Cayman Islands",
    Code2: "KY",
    Code3: "CYM",
    Code3Digits: 136,
  },
  {
    Name: "Central African Republic",
    Code2: "CF",
    Code3: "CAF",
    Code3Digits: 140,
  },
  {
    Name: "Chad",
    Code2: "TD",
    Code3: "TCD",
    Code3Digits: 148,
  },
  {
    Name: "Chile",
    Code2: "CL",
    Code3: "CHL",
    Code3Digits: 152,
  },
  {
    Name: "China",
    Code2: "CN",
    Code3: "CHN",
    Code3Digits: 156,
  },
  {
    Name: "Christmas Island",
    Code2: "CX",
    Code3: "CXR",
    Code3Digits: 162,
  },
  {
    Name: "Cocos (Keeling) Islands",
    Code2: "CC",
    Code3: "CCK",
    Code3Digits: 166,
  },
  {
    Name: "Colombia",
    Code2: "CO",
    Code3: "COL",
    Code3Digits: 170,
  },
  {
    Name: "Comoros",
    Code2: "KM",
    Code3: "COM",
    Code3Digits: 174,
  },
  {
    Name: "Congo (Brazzaville)",
    Code2: "CG",
    Code3: "COG",
    Code3Digits: 178,
  },
  {
    Name: "Cook Islands",
    Code2: "CK",
    Code3: "COK",
    Code3Digits: 184,
  },
  {
    Name: "Costa Rica",
    Code2: "CR",
    Code3: "CRI",
    Code3Digits: 188,
  },
  {
    Name: "C�te d'Ivoire",
    Code2: "CI",
    Code3: "CIV",
    Code3Digits: 384,
  },
  {
    Name: "Croatia",
    Code2: "HR",
    Code3: "HRV",
    Code3Digits: 191,
  },
  {
    Name: "Cuba",
    Code2: "CU",
    Code3: "CUB",
    Code3Digits: 192,
  },
  {
    Name: "Cyprus",
    Code2: "CY",
    Code3: "CYP",
    Code3Digits: 196,
  },
  {
    Name: "Czech Republic",
    Code2: "CZ",
    Code3: "CZE",
    Code3Digits: 203,
  },
  {
    Name: "Democratic Republic of the Congo",
    Code2: "CD",
    Code3: "COD",
    Code3Digits: 180,
  },
  {
    Name: "Denmark",
    Code2: "DK",
    Code3: "DNK",
    Code3Digits: 208,
  },
  {
    Name: "Djibouti",
    Code2: "DJ",
    Code3: "DJI",
    Code3Digits: 262,
  },
  {
    Name: "Dominica",
    Code2: "DM",
    Code3: "DMA",
    Code3Digits: 212,
  },
  {
    Name: "Dominican Republic",
    Code2: "DO",
    Code3: "DOM",
    Code3Digits: 214,
  },
  {
    Name: "Ecuador",
    Code2: "EC",
    Code3: "ECU",
    Code3Digits: 218,
  },
  {
    Name: "Egypt",
    Code2: "EG",
    Code3: "EGY",
    Code3Digits: 818,
  },
  {
    Name: "El Salvador",
    Code2: "SV",
    Code3: "SLV",
    Code3Digits: 222,
  },
  {
    Name: "Equatorial Guinea",
    Code2: "GQ",
    Code3: "GNQ",
    Code3Digits: 226,
  },
  {
    Name: "Eritrea",
    Code2: "ER",
    Code3: "ERI",
    Code3Digits: 232,
  },
  {
    Name: "Estonia",
    Code2: "EE",
    Code3: "EST",
    Code3Digits: 233,
  },
  {
    Name: "Ethiopia",
    Code2: "ET",
    Code3: "ETH",
    Code3Digits: 231,
  },
  {
    Name: "Falkland Islands (Malvinas)",
    Code2: "FK",
    Code3: "FLK",
    Code3Digits: 238,
  },
  {
    Name: "Faroe Islands",
    Code2: "FO",
    Code3: "FRO",
    Code3Digits: 234,
  },
  {
    Name: "Federated States of Micronesia",
    Code2: "FM",
    Code3: "FSM",
    Code3Digits: 583,
  },
  {
    Name: "Fiji",
    Code2: "FJ",
    Code3: "FJI",
    Code3Digits: 242,
  },
  {
    Name: "Finland",
    Code2: "FI",
    Code3: "FIN",
    Code3Digits: 246,
  },
  {
    Name: "France",
    Code2: "FR",
    Code3: "FRA",
    Code3Digits: 250,
  },
  {
    Name: "French Guiana",
    Code2: "GF",
    Code3: "GUF",
    Code3Digits: 254,
  },
  {
    Name: "French Polynesia",
    Code2: "PF",
    Code3: "PYF",
    Code3Digits: 258,
  },
  {
    Name: "French Southern Territories",
    Code2: "TF",
    Code3: "ATF",
    Code3Digits: 260,
  },
  {
    Name: "Gabon",
    Code2: "GA",
    Code3: "GAB",
    Code3Digits: 266,
  },
  {
    Name: "Gambia",
    Code2: "GM",
    Code3: "GMB",
    Code3Digits: 270,
  },
  {
    Name: "Georgia",
    Code2: "GE",
    Code3: "GEO",
    Code3Digits: 268,
  },
  {
    Name: "Germany",
    Code2: "DE",
    Code3: "DEU",
    Code3Digits: 276,
  },
  {
    Name: "Ghana",
    Code2: "GH",
    Code3: "GHA",
    Code3Digits: 288,
  },
  {
    Name: "Gibraltar",
    Code2: "GI",
    Code3: "GIB",
    Code3Digits: 292,
  },
  {
    Name: "Greece",
    Code2: "GR",
    Code3: "GRC",
    Code3Digits: 300,
  },
  {
    Name: "Greenland",
    Code2: "GL",
    Code3: "GRL",
    Code3Digits: 304,
  },
  {
    Name: "Grenada",
    Code2: "GD",
    Code3: "GRD",
    Code3Digits: 308,
  },
  {
    Name: "Guadeloupe",
    Code2: "GP",
    Code3: "GLP",
    Code3Digits: 312,
  },
  {
    Name: "Guam",
    Code2: "GU",
    Code3: "GUM",
    Code3Digits: 316,
  },
  {
    Name: "Guatemala",
    Code2: "GT",
    Code3: "GTM",
    Code3Digits: 320,
  },
  {
    Name: "Guernsey",
    Code2: "GG",
    Code3: "GGY",
    Code3Digits: 831,
  },
  {
    Name: "Guinea",
    Code2: "GN",
    Code3: "GIN",
    Code3Digits: 324,
  },
  {
    Name: "Guinea-Bissau",
    Code2: "GW",
    Code3: "GNB",
    Code3Digits: 624,
  },
  {
    Name: "Guyana",
    Code2: "GY",
    Code3: "GUY",
    Code3Digits: 328,
  },
  {
    Name: "Haiti",
    Code2: "HT",
    Code3: "HTI",
    Code3Digits: 332,
  },
  {
    Name: "Heard Island and Mcdonald Islands",
    Code2: "HM",
    Code3: "HMD",
    Code3Digits: 334,
  },
  {
    Name: "Holy See (Vatican City State)",
    Code2: "VA",
    Code3: "VAT",
    Code3Digits: 336,
  },
  {
    Name: "Honduras",
    Code2: "HN",
    Code3: "HND",
    Code3Digits: 340,
  },
  {
    Name: "Hong Kong (CN)",
    Code2: "HK",
    Code3: "HKG",
    Code3Digits: 344,
  },
  {
    Name: "Hungary",
    Code2: "HU",
    Code3: "HUN",
    Code3Digits: 348,
  },
  {
    Name: "Iceland",
    Code2: "IS",
    Code3: "ISL",
    Code3Digits: 352,
  },
  {
    Name: "India",
    Code2: "IN",
    Code3: "IND",
    Code3Digits: 356,
  },
  {
    Name: "Indonesia",
    Code2: "ID",
    Code3: "IDN",
    Code3Digits: 360,
  },
  {
    Name: "Iran",
    Code2: "IR",
    Code3: "IRN",
    Code3Digits: 364,
  },
  {
    Name: "Iraq",
    Code2: "IQ",
    Code3: "IRQ",
    Code3Digits: 368,
  },
  {
    Name: "Ireland",
    Code2: "IE",
    Code3: "IRL",
    Code3Digits: 372,
  },
  {
    Name: "Isle of Man",
    Code2: "IM",
    Code3: "IMN",
    Code3Digits: 833,
  },
  {
    Name: "Israel",
    Code2: "IL",
    Code3: "ISR",
    Code3Digits: 376,
  },
  {
    Name: "Italy",
    Code2: "IT",
    Code3: "ITA",
    Code3Digits: 380,
  },
  {
    Name: "Jamaica",
    Code2: "JM",
    Code3: "JAM",
    Code3Digits: 388,
  },
  {
    Name: "Japan",
    Code2: "JP",
    Code3: "JPN",
    Code3Digits: 392,
  },
  {
    Name: "Jersey",
    Code2: "JE",
    Code3: "JEY",
    Code3Digits: 832,
  },
  {
    Name: "Jordan",
    Code2: "JO",
    Code3: "JOR",
    Code3Digits: 400,
  },
  {
    Name: "Kazakhstan",
    Code2: "KZ",
    Code3: "KAZ",
    Code3Digits: 398,
  },
  {
    Name: "Kenya",
    Code2: "KE",
    Code3: "KEN",
    Code3Digits: 404,
  },
  {
    Name: "Kiribati",
    Code2: "KI",
    Code3: "KIR",
    Code3Digits: 296,
  },
  {
    Name: "Kuwait",
    Code2: "KW",
    Code3: "KWT",
    Code3Digits: 414,
  },
  {
    Name: "Kyrgyzstan",
    Code2: "KG",
    Code3: "KGZ",
    Code3Digits: 417,
  },
  {
    Name: "Lao PDR",
    Code2: "LA",
    Code3: "LAO",
    Code3Digits: 418,
  },
  {
    Name: "Latvia",
    Code2: "LV",
    Code3: "LVA",
    Code3Digits: 428,
  },
  {
    Name: "Lebanon",
    Code2: "LB",
    Code3: "LBN",
    Code3Digits: 422,
  },
  {
    Name: "Lesotho",
    Code2: "LS",
    Code3: "LSO",
    Code3Digits: 426,
  },
  {
    Name: "Liberia",
    Code2: "LR",
    Code3: "LBR",
    Code3Digits: 430,
  },
  {
    Name: "Libya",
    Code2: "LY",
    Code3: "LBY",
    Code3Digits: 434,
  },
  {
    Name: "Liechtenstein",
    Code2: "LI",
    Code3: "LIE",
    Code3Digits: 438,
  },
  {
    Name: "Lithuania",
    Code2: "LT",
    Code3: "LTU",
    Code3Digits: 440,
  },
  {
    Name: "Luxembourg",
    Code2: "LU",
    Code3: "LUX",
    Code3Digits: 442,
  },
  {
    Name: "Macao (CN)",
    Code2: "MO",
    Code3: "MAC",
    Code3Digits: 446,
  },
  {
    Name: "Macedonia",
    Code2: "MK",
    Code3: "MKD",
    Code3Digits: 807,
  },
  {
    Name: "Madagascar",
    Code2: "MG",
    Code3: "MDG",
    Code3Digits: 450,
  },
  {
    Name: "Malawi",
    Code2: "MW",
    Code3: "MWI",
    Code3Digits: 454,
  },
  {
    Name: "Malaysia",
    Code2: "MY",
    Code3: "MYS",
    Code3Digits: 458,
  },
  {
    Name: "Maldives",
    Code2: "MV",
    Code3: "MDV",
    Code3Digits: 462,
  },
  {
    Name: "Mali",
    Code2: "ML",
    Code3: "MLI",
    Code3Digits: 466,
  },
  {
    Name: "Malta",
    Code2: "MT",
    Code3: "MLT",
    Code3Digits: 470,
  },
  {
    Name: "Marshall Islands",
    Code2: "MH",
    Code3: "MHL",
    Code3Digits: 584,
  },
  {
    Name: "Martinique",
    Code2: "MQ",
    Code3: "MTQ",
    Code3Digits: 474,
  },
  {
    Name: "Mauritania",
    Code2: "MR",
    Code3: "MRT",
    Code3Digits: 478,
  },
  {
    Name: "Mauritius",
    Code2: "MU",
    Code3: "MUS",
    Code3Digits: 480,
  },
  {
    Name: "Mayotte",
    Code2: "YT",
    Code3: "MYT",
    Code3Digits: 175,
  },
  {
    Name: "Mexico",
    Code2: "MX",
    Code3: "MEX",
    Code3Digits: 484,
  },
  {
    Name: "Moldova",
    Code2: "MD",
    Code3: "MDA",
    Code3Digits: 498,
  },
  {
    Name: "Monaco",
    Code2: "MC",
    Code3: "MCO",
    Code3Digits: 492,
  },
  {
    Name: "Mongolia",
    Code2: "MN",
    Code3: "MNG",
    Code3Digits: 496,
  },
  {
    Name: "Montenegro",
    Code2: "ME",
    Code3: "MNE",
    Code3Digits: 499,
  },
  {
    Name: "Montserrat",
    Code2: "MS",
    Code3: "MSR",
    Code3Digits: 500,
  },
  {
    Name: "Morocco",
    Code2: "MA",
    Code3: "MAR",
    Code3Digits: 504,
  },
  {
    Name: "Mozambique",
    Code2: "MZ",
    Code3: "MOZ",
    Code3Digits: 508,
  },
  {
    Name: "Myanmar",
    Code2: "MM",
    Code3: "MMR",
    Code3Digits: 104,
  },
  {
    Name: "Namibia",
    Code2: "NA",
    Code3: "NAM",
    Code3Digits: 516,
  },
  {
    Name: "Nauru",
    Code2: "NR",
    Code3: "NRU",
    Code3Digits: 520,
  },
  {
    Name: "Nepal",
    Code2: "NP",
    Code3: "NPL",
    Code3Digits: 524,
  },
  {
    Name: "Netherlands",
    Code2: "NL",
    Code3: "NLD",
    Code3Digits: 528,
  },
  {
    Name: "Netherlands Antilles",
    Code2: "AN",
    Code3: "ANT",
    Code3Digits: 530,
  },
  {
    Name: "New Caledonia",
    Code2: "NC",
    Code3: "NCL",
    Code3Digits: 540,
  },
  {
    Name: "New Zealand",
    Code2: "NZ",
    Code3: "NZL",
    Code3Digits: 554,
  },
  {
    Name: "Nicaragua",
    Code2: "NI",
    Code3: "NIC",
    Code3Digits: 558,
  },
  {
    Name: "Niger",
    Code2: "NE",
    Code3: "NER",
    Code3Digits: 562,
  },
  {
    Name: "Nigeria",
    Code2: "NG",
    Code3: "NGA",
    Code3Digits: 566,
  },
  {
    Name: "Niue",
    Code2: "NU",
    Code3: "NIU",
    Code3Digits: 570,
  },
  {
    Name: "Norfolk Island",
    Code2: "NF",
    Code3: "NFK",
    Code3Digits: 574,
  },
  {
    Name: "North Korea",
    Code2: "KP",
    Code3: "PRK",
    Code3Digits: 408,
  },
  {
    Name: "Northern Mariana Islands",
    Code2: "MP",
    Code3: "MNP",
    Code3Digits: 580,
  },
  {
    Name: "Norway",
    Code2: "NO",
    Code3: "NOR",
    Code3Digits: 578,
  },
  {
    Name: "Oman",
    Code2: "OM",
    Code3: "OMN",
    Code3Digits: 512,
  },
  {
    Name: "Pakistan",
    Code2: "PK",
    Code3: "PAK",
    Code3Digits: 586,
  },
  {
    Name: "Palau",
    Code2: "PW",
    Code3: "PLW",
    Code3Digits: 585,
  },
  {
    Name: "Palestinian Territory, Occupied",
    Code2: "PS",
    Code3: "PSE",
    Code3Digits: 275,
  },
  {
    Name: "Panama",
    Code2: "PA",
    Code3: "PAN",
    Code3Digits: 591,
  },
  {
    Name: "Papua New Guinea",
    Code2: "PG",
    Code3: "PNG",
    Code3Digits: 598,
  },
  {
    Name: "Paraguay",
    Code2: "PY",
    Code3: "PRY",
    Code3Digits: 600,
  },
  {
    Name: "Peru",
    Code2: "PE",
    Code3: "PER",
    Code3Digits: 604,
  },
  {
    Name: "Philippines",
    Code2: "PH",
    Code3: "PHL",
    Code3Digits: 608,
  },
  {
    Name: "Pitcairn Island",
    Code2: "PN",
    Code3: "PCN",
    Code3Digits: 612,
  },
  {
    Name: "Poland",
    Code2: "PL",
    Code3: "POL",
    Code3Digits: 616,
  },
  {
    Name: "Portugal",
    Code2: "PT",
    Code3: "PRT",
    Code3Digits: 620,
  },
  {
    Name: "Puerto Rico",
    Code2: "PR",
    Code3: "PRI",
    Code3Digits: 630,
  },
  {
    Name: "Qatar",
    Code2: "QA",
    Code3: "QAT",
    Code3Digits: 634,
  },
  {
    Name: "R�union",
    Code2: "RE",
    Code3: "REU",
    Code3Digits: 638,
  },
  {
    Name: "Romania",
    Code2: "RO",
    Code3: "ROU",
    Code3Digits: 642,
  },
  {
    Name: "Russian Federation",
    Code2: "RU",
    Code3: "RUS",
    Code3Digits: 643,
  },
  {
    Name: "Rwanda",
    Code2: "RW",
    Code3: "RWA",
    Code3Digits: 646,
  },
  {
    Name: "Saint Helena",
    Code2: "SH",
    Code3: "SHN",
    Code3Digits: 654,
  },
  {
    Name: "Saint Kitts and Nevis",
    Code2: "KN",
    Code3: "KNA",
    Code3Digits: 659,
  },
  {
    Name: "Saint Lucia",
    Code2: "LC",
    Code3: "LCA",
    Code3Digits: 662,
  },
  {
    Name: "Saint Pierre and Miquelon",
    Code2: "PM",
    Code3: "SPM",
    Code3Digits: 666,
  },
  {
    Name: "Saint Vincent and Grenadines",
    Code2: "VC",
    Code3: "VCT",
    Code3Digits: 670,
  },
  {
    Name: "Saint-Barth�lemy",
    Code2: "BL",
    Code3: "BLM",
    Code3Digits: 652,
  },
  {
    Name: "Saint-Martin (French part)",
    Code2: "MF",
    Code3: "MAF",
    Code3Digits: 663,
  },
  {
    Name: "Samoa",
    Code2: "WS",
    Code3: "WSM",
    Code3Digits: 882,
  },
  {
    Name: "San Marino",
    Code2: "SM",
    Code3: "SMR",
    Code3Digits: 674,
  },
  {
    Name: "Sao Tome and Principe",
    Code2: "ST",
    Code3: "STP",
    Code3Digits: 678,
  },
  {
    Name: "Saudi Arabia",
    Code2: "SA",
    Code3: "SAU",
    Code3Digits: 682,
  },
  {
    Name: "Senegal",
    Code2: "SN",
    Code3: "SEN",
    Code3Digits: 686,
  },
  {
    Name: "Serbia",
    Code2: "RS",
    Code3: "SRB",
    Code3Digits: 688,
  },
  {
    Name: "Seychelles",
    Code2: "SC",
    Code3: "SYC",
    Code3Digits: 690,
  },
  {
    Name: "Sierra Leone",
    Code2: "SL",
    Code3: "SLE",
    Code3Digits: 694,
  },
  {
    Name: "Singapore",
    Code2: "SG",
    Code3: "SGP",
    Code3Digits: 702,
  },
  {
    Name: "Slovakia",
    Code2: "SK",
    Code3: "SVK",
    Code3Digits: 703,
  },
  {
    Name: "Slovenia",
    Code2: "SI",
    Code3: "SVN",
    Code3Digits: 705,
  },
  {
    Name: "Solomon Islands",
    Code2: "SB",
    Code3: "SLB",
    Code3Digits: 90,
  },
  {
    Name: "Somalia",
    Code2: "SO",
    Code3: "SOM",
    Code3Digits: 706,
  },
  {
    Name: "Somaliland",
    Code2: "SO",
    Code3: "SOL",
    Code3Digits: 706,
  },
  {
    Name: "South Africa",
    Code2: "ZA",
    Code3: "ZAF",
    Code3Digits: 710,
  },
  {
    Name: "South Georgia and the South Sandwich Islands",
    Code2: "GS",
    Code3: "SGS",
    Code3Digits: 239,
  },
  {
    Name: "South Korea",
    Code2: "KR",
    Code3: "KOR",
    Code3Digits: 410,
  },
  {
    Name: "South Sudan",
    Code2: "SS",
    Code3: "SSD",
    Code3Digits: 728,
  },
  {
    Name: "Spain",
    Code2: "ES",
    Code3: "ESP",
    Code3Digits: 724,
  },
  {
    Name: "Sri Lanka",
    Code2: "LK",
    Code3: "LKA",
    Code3Digits: 144,
  },
  {
    Name: "Sudan",
    Code2: "SD",
    Code3: "SDN",
    Code3Digits: 736,
  },
  {
    Name: "Suriname",
    Code2: "SR",
    Code3: "SUR",
    Code3Digits: 740,
  },
  {
    Name: "Svalbard and Jan Mayen Islands",
    Code2: "SJ",
    Code3: "SJM",
    Code3Digits: 744,
  },
  {
    Name: "Swaziland",
    Code2: "SZ",
    Code3: "SWZ",
    Code3Digits: 748,
  },
  {
    Name: "Sweden",
    Code2: "SE",
    Code3: "SWE",
    Code3Digits: 752,
  },
  {
    Name: "Switzerland",
    Code2: "CH",
    Code3: "CHE",
    Code3Digits: 756,
  },
  {
    Name: "Syrian Arab Republic (Syria)",
    Code2: "SY",
    Code3: "SYR",
    Code3Digits: 760,
  },
  {
    Name: "Taiwan (CN)",
    Code2: "TW",
    Code3: "TWN",
    Code3Digits: 158,
  },
  {
    Name: "Tajikistan",
    Code2: "TJ",
    Code3: "TJK",
    Code3Digits: 762,
  },
  {
    Name: "Tanzania",
    Code2: "TZ",
    Code3: "TZA",
    Code3Digits: 834,
  },
  {
    Name: "Thailand",
    Code2: "TH",
    Code3: "THA",
    Code3Digits: 764,
  },
  {
    Name: "Timor-Leste",
    Code2: "TL",
    Code3: "TLS",
    Code3Digits: 626,
  },
  {
    Name: "Togo",
    Code2: "TG",
    Code3: "TGO",
    Code3Digits: 768,
  },
  {
    Name: "Tokelau",
    Code2: "TK",
    Code3: "TKL",
    Code3Digits: 772,
  },
  {
    Name: "Tonga",
    Code2: "TO",
    Code3: "TON",
    Code3Digits: 776,
  },
  {
    Name: "Trinidad and Tobago",
    Code2: "TT",
    Code3: "TTO",
    Code3Digits: 780,
  },
  {
    Name: "Tunisia",
    Code2: "TN",
    Code3: "TUN",
    Code3Digits: 788,
  },
  {
    Name: "Turkey",
    Code2: "TR",
    Code3: "TUR",
    Code3Digits: 792,
  },
  {
    Name: "Turkmenistan",
    Code2: "TM",
    Code3: "TKM",
    Code3Digits: 795,
  },
  {
    Name: "Turks and Caicos Islands",
    Code2: "TC",
    Code3: "TCA",
    Code3Digits: 796,
  },
  {
    Name: "Tuvalu",
    Code2: "TV",
    Code3: "TUV",
    Code3Digits: 798,
  },
  {
    Name: "Uganda",
    Code2: "UG",
    Code3: "UGA",
    Code3Digits: 800,
  },
  {
    Name: "Ukraine",
    Code2: "UA",
    Code3: "UKR",
    Code3Digits: 804,
  },
  {
    Name: "United Arab Emirates",
    Code2: "AE",
    Code3: "ARE",
    Code3Digits: 784,
  },
  {
    Name: "United Kingdom",
    Code2: "GB",
    Code3: "GBR",
    Code3Digits: 826,
  },
  {
    Name: "United States Minor Outlying Islands",
    Code2: "UM",
    Code3: "UMI",
    Code3Digits: 581,
  },
  {
    Name: "United States of America",
    Code2: "US",
    Code3: "USA",
    Code3Digits: 840,
  },
  {
    Name: "Uruguay",
    Code2: "UY",
    Code3: "URY",
    Code3Digits: 858,
  },
  {
    Name: "Uzbekistan",
    Code2: "UZ",
    Code3: "UZB",
    Code3Digits: 860,
  },
  {
    Name: "Vanuatu",
    Code2: "VU",
    Code3: "VUT",
    Code3Digits: 548,
  },
  {
    Name: "Venezuela",
    Code2: "VE",
    Code3: "VEN",
    Code3Digits: 862,
  },
  {
    Name: "Vietnam",
    Code2: "VN",
    Code3: "VNM",
    Code3Digits: 704,
  },
  {
    Name: "Virgin Islands, US",
    Code2: "VI",
    Code3: "VIR",
    Code3Digits: 850,
  },
  {
    Name: "Wallis and Futuna Islands",
    Code2: "WF",
    Code3: "WLF",
    Code3Digits: 876,
  },
  {
    Name: "Western Sahara",
    Code2: "EH",
    Code3: "ESH",
    Code3Digits: 732,
  },
  {
    Name: "Yemen",
    Code2: "YE",
    Code3: "YEM",
    Code3Digits: 887,
  },
  {
    Name: "Zambia",
    Code2: "ZM",
    Code3: "ZMB",
    Code3Digits: 894,
  },
  {
    Name: "Zimbabwe",
    Code2: "ZW",
    Code3: "ZWE",
    Code3Digits: 716,
  },
];